apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-eviction-extender
  namespace: kube-eviction-extender

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-eviction-extender
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - update
      - patch

  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-eviction-extender
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-eviction-extender
subjects:
  - kind: ServiceAccount
    name: k8s-eviction-extender
    namespace: kube-eviction-extender
