apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: deny-cron-create
webhooks:
- name: deny.cron.create
  rules:
  - apiGroups:
    - "batch"
    apiVersions:
    - v1beta1
    operations:
    - "CREATE"
    resources:
    - cronjobs
  # Default failurePolicy is not fail.
  failurePolicy: Fail
  clientConfig:
    service:
      namespace: default
      name: kube-vwh-service
      path: /deny-cronjob-createx
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEyTVRRd01nWURWUVFEREN0dmNHVnUKYzJocFpuUXRjMlZ5ZG1salpTMXpaWEoyYVc1bkxYTnBaMjVsY2tBeE5UVXdOakF6Tmprek1CNFhEVEU1TURJeApPVEU1TVRRMU1sb1hEVEU1TURNd01URTVNVFExTTFvd05qRTBNRElHQTFVRUF3d3JiM0JsYm5Ob2FXWjBMWE5sCmNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVFUxTURZd016WTVNekNDQVNJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnRVBBRENDQVFvQ2dnRUJBSnl0dTlIM2dpakJCYjBwTWtwMkJHRnd2amRyNDBRa3dma2FxVXpubVNqVwpoeWpJWjV5SEl3ei91VzROMDVlZ2dxVGN1WFA2c1diaENoSlNMYmk4WVpvNjY2b1BSWk9ZTURPOEdQUnNYSEpYCnBCMGZrbnJ2d2ZZVEhvcFNxajZwNEVQNncyTmVYczRrWHNDOU42UEl6aUNreTAxOGl1RnJ3NVZiM1loc09CanAKelFKck94c1FjVkNQcVplNVpjbTl3cGFmODF2M09kQ1VDQ2hoeVAyYTRZYlBmc3BsVXZVVmxqUytJa1lWTnBiQgoyaTBVZGwyaUVXWkd3c2hjQ1dJZFAwL3JudFBzVVNlT3pZclZEeGltYUFYTUQyRG8yNUovdWNIRVhHWW5GNmxLCm14elpUSWd0TTlhMTJ0REZQNnNyaWxlbk8yeERwZkcrMXNhdTFVUk5DTThDQXdFQUFhTWpNQ0V3RGdZRFZSMFAKQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUFMawo3RXpZOXZpYWs0VDFmOGJFWENYekdMT3NJQU9mU2NmbTBnOFVCdmZBdEgveFZVZ1FTSTVyUCtoVmdrQTRsdFF4ClkvdWtyUmRoM2FhNW82TTFIVk44T1lqMFpjWE5GUUQ5b0NLcWd4QjVmWitFd29yTXhIVmNrQVp4blhpYXhJVUEKTlJqc0R3Vm9HZEZlVG1IU241ZnhuMnpkZ29HNXlTRmZYQllJT25Kd2xxcTUrWEFCWFZXLzdOODN3T0xidi9BSwpsZ3VXb0FjaEhPbFM5d3ByV05OaW51RDlKQit4VFA3eWkzREpZZm1CTGQ4R0ZrQzE2V3pubUZjazErc3J6T3FICm5LaHNlRHgxMWRRVTQ3WDRURGZmUW1QTlJ6cFZXWjdnNTlnUzU4RnZ0cEFEeFQ3UFhSanFyalVNaFpMdEFSaFIKbkJFSjdNK0toRTBaQVFCVldtTT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
